# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    ports:
    -"9999:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    restart: always





































































